### ISSUE TITLE
Latest nightly build crashes on start

### ISSUE THREAD

**Issue by JesusLopTem** [lutraconsulting/qgis-mac-packager#25] opened 2018-11-16 11:25 UTC
**Describe the bug**
Latest nightly build (qgis_nightly_master_20181116_051333) crashes on start on 10.11.6
**Additional information**
From terminal: LSOpenURLsWithRole() failed with error -10810 for the file /Applications/QGIS.app.
 codesign --verify --verbose /Applications/QGIS.app
/Applications/QGIS.app: valid on disk
/Applications/QGIS.app: satisfies its Designated Requirement

**Comment by saberraz** [comment] 2018-11-16 11:44
I can confirm that. At the moment, everything is broken for 10.13. We are reconsidering support for >10.13 as there are so many upstream blockers in Python, Homebrew and other packages.

**Comment by JesusLopTem** [comment] 2018-11-16 12:17
Previous nightly (qgis_nightly_master_20181116_012525) works fine except for the known python issues

**Comment by PeterPetrik** [comment] 2018-11-16 12:21
new build will be in ~hours, hopefully with the fix

**Comment by JesusLopTem** [comment] 2018-11-16 13:20
No luck. qgis_nightly_master_20181116_063515 crash again, error -10810...

**Comment by saberraz** [comment] 2018-11-16 15:39
![image](https://user-images.githubusercontent.com/2649047/48631105-c3e95000-e9b5-11e8-8e67-18dd972966d3.png)

**Comment by saberraz** [comment] 2018-11-17 08:30
This may well be due to python path. I have manually exported the path and ran the app from terminal and all works (in 10.13).

**Comment by JesusLopTem** [comment] 2018-11-17 08:48
How can I export the path?

**Comment by saberraz** [comment] 2018-11-17 08:58
Which MacOS version are you using?

**Comment by JesusLopTem** [comment] 2018-11-17 09:10
10.11.6

**Comment by saberraz** [comment] 2018-11-17 09:11
Check with #22  This is an upstream issue with Python.

**Comment by JesusLopTem** [comment] 2018-11-17 09:31
Thanks Sab!

**Comment by JesusLopTem** [comment] 2018-11-19 16:50
qgis_nightly_master_20181119_111923 crash again on startup, latest nightly that don't crash in OSX 10.11.6 is qgis_nightly_master_20181116_161910

**Comment by saberraz** [comment] 2018-11-19 17:03
Hi @JesusLopTem 
I can confirm the issue. Lets wait for @PeterPetrik before opening the issue. I think he is working on it.

**Comment by PeterPetrik** [comment] 2018-11-19 18:08
@JesusLopTem thanks for staying in testing, hopefully clean build in ~hour can fix this as last time
if so, I would probably avoid incremental builds

**Comment by JesusLopTem** [comment] 2018-11-19 22:12
No problem @PeterPetrik, happy to help. Unfortunately qgis_nightly_master_20181119_142421 doesn't work. From the problem report:

Crashed Thread:        0  Dispatch queue: com.apple.main-thread

Exception Type:        EXC_BAD_INSTRUCTION (SIGILL)
Exception Codes:       0x0000000000000001, 0x0000000000000000
Exception Note:        EXC_CORPSE_NOTIFY

Application Specific Information:
/Applications/QGIS.app/Contents/MacOS/lib/libgdal.20.dylib

**Comment by JesusLopTem** [comment] 2018-11-20 10:03
Latest three nightly masters (20181120_025125, 20181120_032906, 20181120_040246) keep crashing on start. 
```
Crashed Thread:        0  Dispatch queue: com.apple.main-thread

Exception Type:        EXC_BAD_INSTRUCTION (SIGILL)
Exception Codes:       0x0000000000000001, 0x0000000000000000
Exception Note:        EXC_CORPSE_NOTIFY

Application Specific Information:
/Applications/QGIS.app/Contents/MacOS/lib/libgdal.20.dylib

Thread 0 Crashed:: Dispatch queue: com.apple.main-thread
0   libgdal.20.dylib              	0x00000001081d37e7 _GLOBAL__sub_I_minidriver.cpp + 4
1   dyld                          	0x00007fff6fa7010b ImageLoaderMachO::doModInitFunctions(ImageLoader::LinkContext const&) + 265
2   dyld                          	0x00007fff6fa70284 ImageLoaderMachO::doInitialization(ImageLoader::LinkContext const&) + 40
3   dyld                          	0x00007fff6fa6c8bd ImageLoader::recursiveInitialization(ImageLoader::LinkContext const&, unsigned int, ImageLoader::InitializerTimingList&, ImageLoader::UninitedUpwards&) + 305
4   dyld                          	0x00007fff6fa6c852 ImageLoader::recursiveInitialization(ImageLoader::LinkContext const&, unsigned int, ImageLoader::InitializerTimingList&, ImageLoader::UninitedUpwards&) + 198
5   dyld                          	0x00007fff6fa6c852 ImageLoader::recursiveInitialization(ImageLoader::LinkContext const&, unsigned int, ImageLoader::InitializerTimingList&, ImageLoader::UninitedUpwards&) + 198
6   dyld                          	0x00007fff6fa6c743 ImageLoader::processInitializers(ImageLoader::LinkContext const&, unsigned int, ImageLoader::InitializerTimingList&, ImageLoader::UninitedUpwards&) + 127
7   dyld                          	0x00007fff6fa6c9b3 ImageLoader::runInitializers(ImageLoader::LinkContext const&, ImageLoader::InitializerTimingList&) + 75
8   dyld                          	0x00007fff6fa5f0f1 dyld::initializeMainExecutable() + 208
9   dyld                          	0x00007fff6fa62d98 dyld::_main(macho_header const*, unsigned long, int, char const**, char const**, char const**, unsigned long*) + 3596
10  dyld                          	0x00007fff6fa5e276 dyldbootstrap::start(macho_header const*, int, char const**, long, macho_header const*, unsigned long*) + 512
11  dyld                          	0x00007fff6fa5e036 _dyld_start + 54

Thread 0 crashed with X86 Thread State (64-bit):
  rax: 0x0000000000000001  rbx: 0x00000001081d37e3  rcx: 0x00007fff5ed2bb78  rdx: 0x00007fff5ed2bad8
  rdi: 0x0000000000000001  rsi: 0x00007fff5ed2bac8  rbp: 0x00007fff5ed27a80  rsp: 0x00007fff5ed27a80
   r8: 0x00007fff6fa96690   r9: 0x00007fff742fc0c8  r10: 0x00000000ffffffff  r11: 0xffffffff00000000
  r12: 0x00000001089d80a0  r13: 0x00007fff6fa965c8  r14: 0x00007fff6faa1f78  r15: 0x0000000000000003
  rip: 0x00000001081d37e7  rfl: 0x0000000000010246  cr2: 0x00000001081d37e3
  
Logical CPU:     2
Error Code:      0x00000000
Trap Number:     6

```

**Comment by saberraz** [comment] 2018-11-20 13:02
works with https://www.dropbox.com/sh/cc3615b1zd7ruwz/AAA-y5bGLnhYYM9J-MmYQum5a/qgis_nightly_master_20181120_072113.dmg?dl=0

**Closed by saberraz** 2018-11-20 13:02 UTC
Labels: 10.11, CRASH, bug

**Comment by PeterPetrik** [comment] 2018-11-20 13:05
@JesusLopTem https://www.dropbox.com/s/riczwaoe599r2fl/qgis_nightly_master_20181120_072113.dmg?dl=0

this one should work

**Comment by JesusLopTem** [comment] 2018-11-20 13:16
No more crash. Thanks!
