### ISSUE TITLE
GDAL Python scripts don't work out the box

### ISSUE THREAD

**Issue by timlinux** [lutraconsulting/qgis-mac-packager#64] opened 2019-02-15 19:22 UTC
Using QGIS 3.4.4 trying to merge two rasters:

```
Processing algorithm…
Algorithm 'Merge' starting…
Input parameters:
{ 'DATA_TYPE' : 4, 'INPUT' : ['/Users/timlinux/gisdata/Mauritius/SRTM/S20E057.tif','/Users/timlinux/gisdata/Mauritius/SRTM/S21E057.tif'], 'NODATA_INPUT' : None, 'NODATA_OUTPUT' : None, 'OPTIONS' : '', 'OUTPUT' : '/Users/timlinux/gisdata/Mauritius/SRTM/mauritius_srtm.tif', 'PCT' : False, 'SEPARATE' : False }

GDAL command:
gdal_merge.py -ot Int32 -of GTiff -o /Users/timlinux/gisdata/Mauritius/SRTM/mauritius_srtm.tif --optfile /var/folders/g6/fnh1vyx13q728xq52nw7yx400000gn/T/processing_a8242990f1714f70ac83bea2bcef79c0/mergeInputFiles.txt
GDAL command output:
/bin/sh: gdal_merge.py: command not found

Execution completed in 0.13 seconds
Results:
{'OUTPUT': <QgsProcessingOutputLayerDefinition {'sink':/Users/timlinux/gisdata/Mauritius/SRTM/mauritius_srtm.tif, 'createOptions': {'fileEncoding': 'System'}}>}

Loading resulting layers
The following layers were not correctly generated.<ul><li>/Users/timlinux/gisdata/Mauritius/SRTM/mauritius_srtm.tif</li></ul>You can check the 'Log Messages Panel' in QGIS main window to find more information about the execution of the algorithm.
```

Would be nice if it could work out the box with proper package search paths for GDAL python tools

**Comment by timlinux** [comment] 2019-02-15 19:43
Similar issue for gdal_buildvrt:

```
Processing algorithm…
Algorithm 'Build virtual raster' starting…
Input parameters:
{ 'ADD_ALPHA' : False, 'ASSIGN_CRS' : None, 'INPUT' : ['/Users/timlinux/gisdata/Mauritius/SRTM/S20E057.tif','/Users/timlinux/gisdata/Mauritius/SRTM/S21E057.tif'], 'OUTPUT' : '/var/folders/g6/fnh1vyx13q728xq52nw7yx400000gn/T/processing_a8242990f1714f70ac83bea2bcef79c0/02e6f771606a442ab2cbc51205a6ebc6/OUTPUT.vrt', 'PROJ_DIFFERENCE' : False, 'RESAMPLING' : 0, 'RESOLUTION' : 0, 'SEPARATE' : True }

GDAL command:
gdalbuildvrt -resolution average -separate -r nearest -input_file_list /var/folders/g6/fnh1vyx13q728xq52nw7yx400000gn/T/processing_a8242990f1714f70ac83bea2bcef79c0/buildvrtInputFiles.txt /var/folders/g6/fnh1vyx13q728xq52nw7yx400000gn/T/processing_a8242990f1714f70ac83bea2bcef79c0/02e6f771606a442ab2cbc51205a6ebc6/OUTPUT.vrt
GDAL command output:
/bin/sh: gdalbuildvrt: command not found

Execution completed in 0.12 seconds
Results:
{'OUTPUT': <QgsProcessingOutputLayerDefinition {'sink':/var/folders/g6/fnh1vyx13q728xq52nw7yx400000gn/T/processing_a8242990f1714f70ac83bea2bcef79c0/02e6f771606a442ab2cbc51205a6ebc6/OUTPUT.vrt, 'createOptions': {'fileEncoding': 'System'}}>}

Loading resulting layers
The following layers were not correctly generated.<ul><li>/var/folders/g6/fnh1vyx13q728xq52nw7yx400000gn/T/processing_a8242990f1714f70ac83bea2bcef79c0/02e6f771606a442ab2cbc51205a6ebc6/OUTPUT.vrt</li></ul>You can check the 'Log Messages Panel' in QGIS main window to find more information about the execution of the algorithm.
```

**Comment by saberraz** [comment] 2019-02-17 11:29
@timlinux I tried with the latest PR and all worked fine. Could you give this a try and report back:
https://www.dropbox.com/sh/qcr9a6ry25n4x91/AAD2VLOhb6CllBcptCCMAVz_a/qgis_pr_final-3_4_4_20190214_111602.dmg?dl=0

**Comment by PeterPetrik** [comment] 2019-02-18 07:04
duplicate of https://github.com/lutraconsulting/qgis-mac-packager/issues/60

**Closed** 2019-02-18 18:03 UTC
Labels: MacOS >= 10.13, duplicate, feedback, processing
