### ISSUE TITLE
Grass76 tools not working

### ISSUE THREAD

**Issue by mapninja** [lutraconsulting/qgis-mac-packager#50] opened 2018-12-19 04:39 UTC
OS: 10.14.1
Builds: https://www.dropbox.com/sh/qcr9a6ry25n4x91/AABUVhV04SPIlVrUWQFu6oVTa/qgis_pr_final-3_4_2_20181213_133326.dmg

https://www.dropbox.com/sh/qcr9a6ry25n4x91/AAD3FQLoeuqqjY8y1KgJ-jB7a/qgis_pr_final-3_4_2_20181218_123912.dmg

I'm testing installs by running the random point in extent from the QGIS tools, then v.voronoi from GRASS tools. I haven't seen a version able to run GRASS tools, yet.  

Typical error:
```
2018-12-18T20:24:46     INFO    GRASS GIS 7 execution commands
             g.proj -c proj4="+proj=merc +a=6378137 +b=6378137 +lat_ts=0.0 +lon_0=0.0 +x_0=0.0 +y_0=0 +k=1.0 +units=m +nadgrids=@null +wktext +no_defs"
             v.in.ogr min_area=0.0001 snap=-1.0 input="/private/var/folders/f3/0prmkq7962795yfpwsmvh2100000gq/T/processing_19bd86a7cd1e4ef393497be61b147698/267016becafa493d9e19eea48d8cca1d/input.shp" output="vector_5c19c80e59df28" --overwrite -o
             g.region n=7323584.629008968 s=4531517.1646392355 e=-7230559.64415352 w=-10028075.457266835
             v.voronoi input=vector_5c19c80e59df28 smoothness=0.25 thin=-1 output=outputebc6def7436e48c1b3b6bfb0f6fd2acb --overwrite
             v.out.ogr -c type="auto" input="outputebc6def7436e48c1b3b6bfb0f6fd2acb" output="/private/var/folders/f3/0prmkq7962795yfpwsmvh2100000gq/T/processing_19bd86a7cd1e4ef393497be61b147698/a6e9f8a160254c338eb54dd74ef5c908/output.gpkg" format="GPKG" --overwrite
2018-12-18T20:24:46     INFO    GRASS GIS 7 execution console output
             /Applications/QGIS3.4.2.app/Contents/Resources/grass7/bin/grass74: line 5: /usr/local/Cellar/grass7/7.4.3_2/libexec/bin/grass74: No such file or directory
             
             /Applications/QGIS3.4.2.app/Contents/Resources/grass7/bin/grass74: line 5: exec: /usr/local/Cellar/grass7/7.4.3_2/libexec/bin/grass74: cannot execute: No such file or directory
             
             /Applications/QGIS3.4.2.app/Contents/Resources/grass7/bin/grass74: line 5: /usr/local/Cellar/grass7/7.4.3_2/libexec/bin/grass74: No such file or directory
             /Applications/QGIS3.4.2.app/Contents/Resources/grass7/bin/grass74: line 5: exec: /usr/local/Cellar/grass7/7.4.3_2/libexec/bin/grass74: cannot execute: No such file or directory
``` .

**Comment by saberraz** [comment] 2018-12-19 05:34
@mapninja I can confirm the issue.

@PeterPetrik since you have updated the apps to have version numbers, the link in processing is still referring to QGIS.app:
![image](https://user-images.githubusercontent.com/2649047/50200891-c4c42780-034f-11e9-978a-946717701ef1.png)

**Comment by PeterPetrik** [comment] 2018-12-21 11:39
ok, it looks like that python-part of the grass-7 from homebrew depends on python2 
https://github.com/OSGeo/homebrew-osgeo4mac/blob/master/Formula/grass7.rb#L58

more: 
https://github.com/OSGeo/homebrew-osgeo4mac/issues/228
and 
https://github.com/OSGeo/homebrew-osgeo4mac/issues/452

Since this whole package is based on python3 (bundled), so first 
1. we need to make sure GRASS is compatible with Python3
2. fix homebrew to use GRASS with Python3 
3. update this package

**Comment by Spartacus1** [comment] 2018-12-26 19:38
Any new on this issue? I've tried to compile grass7 with python but no luck. The modules seem to work but fail to write the resulting files. 
What path are you using in the tools settings?

**Comment by neteler** [comment] 2018-12-27 12:32
> Any new on this issue? I've tried to compile grass7 with python 3 but no luck. 

Which GRASS GIS version did you try?

**Comment by Spartacus1** [comment] 2018-12-27 14:06
I my case, the installed Grass7 version is 7.4.3-3.

**Comment by neteler** [comment] 2018-12-27 16:56
> In my case, the installed Grass7 version is 7.4.3-3.

This will not work with Python3, see #568 - you need at least GRASS GIS 7.7.

**Comment by neteler** [comment] 2018-12-27 22:47
I guess it would be sufficient to update the version number here accordingly:
https://github.com/OSGeo/homebrew-osgeo4mac/blob/master/Formula/grass7.rb

**Comment by Spartacus1** [comment] 2018-12-30 23:57
No luck here...

**Comment by neteler** [comment] 2019-01-05 12:08
Weekly snapshots are available here: https://grass.osgeo.org/grass77/source/snapshot/

**Comment by PeterPetrik** [comment] 2019-01-07 07:10
@neteler what do you suggest for QGIS 3.6 LTR ? I am confused what I am supposed to do now. 
If I understand it correctly, currently there is no released-tagged version of GRASS that is python3-only. So 
a) do we expect that there will be such (pre-)release so I can wait and then integrate that one OR 
b) should I just bundle master/trunk (which is obviously far far from ideal because I am bundling some random version that is not tested for release, etc.)
thanks

**Comment by neteler** [comment] 2019-01-07 10:37
> @neteler what do you suggest for QGIS 3.6 LTR ? I am confused what I am supposed to do now.

ok, let's try to figure it out together :)

> If I understand it correctly, currently there is no released-tagged version of GRASS that is python3-only.

That's correct as of early Jan 2019.

> So
> a) do we expect that there will be such (pre-)release so I can wait and then integrate that one OR
> b) should I just bundle master/trunk (which is obviously far far from ideal because I am bundling some random version that is not tested for release, etc.)

While a) is definitely better (what is the timeline for you?), b) could be an interim option in order to prepare things.

I have drafted a GRASS GIS 7.8.0 roadmap right now: https://trac.osgeo.org/grass/milestone/7.8.0

> thanks

**Comment by PeterPetrik** [comment] 2019-01-07 10:49
I will have time to work on this installed after QGIS Feature freeze (so in February). So maybe the plan could be 

1) in february, use the release-7.8.0 branch in nightly builds
2) switch to released version once released and integrated into osgeo homebrew
3) have 7.8.0 official in QGIS 3.6 is all goes well?

sounds feasible?

**Comment by neteler** [comment] 2019-01-08 21:33
To me it sounds very good. From the GRASS GIS side we try to speed up as much as possible.

**Comment by PeterPetrik** [comment] 2019-02-11 14:05
@neteler do you know if master from https://github.com/GRASS-GIS/grass-ci.git is good for my tests or I need to use svn release-7.8.0 branch. I assume there is no RC for 7.8 with python3 support yet.

**Comment by grass-svn2git** [comment] 2019-02-11 15:13
Well, we use it for creating docker images automatically (see  https://hub.docker.com/r/mundialis/grass-gis7-trunk). I think it is ok for this purpose. Then, as soon as a release branch is created (i.e. RC) then you could simply switch the path to the code.

**Comment by neteler** [comment] 2019-02-14 20:21
Well, we use it for creating docker images automatically (see https://hub.docker.com/r/mundialis/grass-gis7-trunk). I think it is ok for this purpose. Then, as soon as a release branch is created (i.e. RC) then you could simply switch the path to the code.

**Comment by PeterPetrik** [comment] 2019-02-18 11:06
related https://github.com/OSGeo/homebrew-osgeo4mac/issues/706

**Comment by PeterPetrik** [comment] 2019-02-19 13:09
OK, I found out that we have 2 problems here 
1) some scripts (grass76 from homebrew and grass76 from grass installation) used incorrect python/environment to run. This caused various problems to run some tools
2) some grass76 tools are just not working with python3 and this should be fixed in 7.8 release in the future.

I have fixed 1) in changeset https://github.com/lutraconsulting/qgis-mac-packager/commit/055ff59a266e2a4bba075d2343ff763f8e61c167 and managed to run v.buffer for a point successfully.

@neteler @saberraz can you try https://www.dropbox.com/s/0y6j4ddw17uio2i/qgis_pr_final-3_4_4_20190219_070032.dmg?dl=0

I propose to close this ticket and wait for regular 7.8 release for other grass-upstream related bugs.

**Comment by saberraz** [comment] 2019-02-19 13:40
@PeterPetrik I tested some of the more common algs and all working fine. I agree that we should close this ticket. Once GRASS is ported to Python 3, all should be working on macOS too.

**Closed by saberraz** 2019-02-19 13:40 UTC
Labels: MacOS >= 10.13, bug, feedback

**Comment by neteler** [comment] 2019-05-20 07:42
Just a status update: we finally migrated from SVN to GitHub:
 
https://github.com/OSGeo/grass

Master is Python-3 compatible (last bugs to be identified), in ~ 2 weeks a new release_branch78 will be created from master.
