### ISSUE TITLE
GDAL not working - Bug #52 back?

### ISSUE THREAD

**Issue by kobben** [lutraconsulting/qgis-mac-packager#85] opened 2019-05-17 12:03 UTC
Now in 3.6 the problem is back again (at least for GDAL)
qgis_pr_final-3_6_0_20190222_124710.dmg 
macOS 10.14.4 (18E226)

Tried running GDAL Hillshade:
GDAL command:
gdaldem hillshade /var/folders/zy/jv8h0qxs5blgxh57bn2fk7q00000gp/T/N19W072.hgt /private/var/folders/zy/jv8h0qxs5blgxh57bn2fk7q00000gp/T/processing_03e328d8c11a4fa19d2ca0b9c753325b/6a36f1dd3d5f45b499bd6227b7154483/OUTPUT.tif -of GTiff -b 1 -z 1.0 -s 1.0 -az 315.0 -alt 45.0
GDAL command output:
dyld: Symbol not found: _iconv
Referenced from: /usr/lib/libcups.2.dylib
Expected in: /Applications/QGIS3.6.app/Contents/MacOS/lib/libiconv.2.dylib
in /usr/lib/libcups.2.dylib

both .2.dylib files are present....

**Comment by PeterPetrik** [comment] 2019-05-20 07:54
duplicate of https://github.com/qgis/QGIS-Mac-Packager/issues/1

**Closed by PeterPetrik** 2019-05-20 07:54 UTC
Labels: bug
