### ISSUE TITLE
Hidden 'Save Project' window at startup

### ISSUE THREAD

**Issue by piulintos** [lutraconsulting/qgis-mac-packager#66] opened 2019-02-17 08:47 UTC
**Description of the bug**
When opening QGIS, the app loads, we can see the list with previous projects, but the QGIS opening logo doesn't disappear, and the app doesn't seems to respond. A 'Save Project’ window is hidden behind the QGIS opening logo, and we must hit Return and then cancel the Save option before the QGIS opening logo can be closed and we can use the application. 

This happens with all the Nightly Build versions I have tested, and now also with the Latest Release 3.4.4. 

**Additional information**

- **Link to the installed package:** https://www.dropbox.com/s/26abu37gvtotfky/qgis_pr_final-3_4_4_20190214_041422.dmg?dl=0
- **MacOS version:** 10.14.3
- **Installation location of QGIS:** /Applications/QGIS3.4.4.app
- **Crash report:** No crash.

**Comment by saberraz** [comment] 2019-02-17 11:34
I am having similar issue with other tools too. Some windows randomly move to background and I need to minimise QGIS main window to be able to see them.
![disappearing_window](https://user-images.githubusercontent.com/2649047/52912332-e8501380-32a7-11e9-858f-b95dfc4d6990.gif)

**Comment by PeterPetrik** [comment] 2019-02-18 07:08
probably duplicate of https://github.com/lutraconsulting/qgis-mac-packager/issues/39

**Comment by piulintos** [comment] 2019-02-18 16:02
I believe the issue I reported is not exactly the same as a window randomly moving to background, as the "Save project" window, hidden under the QGIS logo, is activated at startup, before I can even start interacting with QGIS. But I believe the issue has to do with some python plugin, as the problem was solved by testing QGIS on a clean user account (see [#65](https://github.com/lutraconsulting/qgis-mac-packager/issues/65))

**Closed** 2019-02-18 16:13 UTC
Labels: MacOS >= 10.13, bug
